let colors = {
  "gray-0": "var(--color-gray-0)",
  "gray-1": "var(--color-gray-1)",
  "gray-2": "var(--color-gray-2)",
  "gray-3": "var(--color-gray-3)",
  "gray-4": "var(--color-gray-4)",
  "gray-5": "var(--color-gray-5)",
  "gray-6": "var(--color-gray-6)",
  "gray-7": "var(--color-gray-7)",
  "gray-8": "var(--color-gray-8)",
  "gray-9": "var(--color-gray-9)",
  "danger-1": "var(--color-danger-1)",
  "danger-2": "var(--color-danger-2)",
  "danger-3": "var(--color-danger-3)",
  "danger-4": "var(--color-danger-4)",
  "danger-5": "var(--color-danger-5)",
  "primary-1": "var(--color-primary-1)",
  "primary-2": "var(--color-primary-2)",
  "primary-3": "var(--color-primary-3)",
  "primary-4": "var(--color-primary-4)",
  "primary-5": "var(--color-primary-5)",
  "success-1": "var(--color-success-1)",
  "success-2": "var(--color-success-2)",
  "success-3": "var(--color-success-3)",
  "success-4": "var(--color-success-4)",
  "success-5": "var(--color-success-5)",
  "warning-1": "var(--color-warning-1)",
  "warning-2": "var(--color-warning-2)",
  "warning-3": "var(--color-warning-3)",
  "warning-4": "var(--color-warning-4)",
  "warning-5": "var(--color-warning-5)",
  "transparent": "transparent",
  "current": "currentColor",
  "inherit": "inherit",
};

module.exports = {
  colors: colors,
  screens: {},
  fonts: {
    "sans": [
      "-apple-system",
      "BlinkMacSystemFont",
      "Helvetica Neue",
      "Ubuntu",
      "Roboto",
      "Segoe UI",
      "sans-serif",
    ],
    "mono": [
      "SFMono-Regular",
      "Menlo",
      "Ubuntu Mono",
      "Liberation Mono",
      "Consolas",
      "Courier",
      "monospace",
    ],
  },
  textSizes: {
    "35": "35px",
    "30": "30px",
    "26": "26px",
    "23": "23px",
    "20": "20px",
    "17": "17px",
    "15": "15px",
    "13": "13px",
    "11": "11px",
    "10": "10px",
    "9": "9px",
  },
  fontWeights: {
    "normal": 400,
    "medium": 500,
    "semi-bold": 600,
    "bold": 700,
  },
  leading: {
    "16": "16px",
    "20": "20px",
    "24": "24px",
    "28": "28px",
    "32": "32px",
    "40": "40px",
    "44": "44px",
    "r1p5": "1.5",
  },
  tracking: {},
  textColors: colors,
  backgroundColors: colors,
  backgroundSize: {},
  borderWidths: {
    default: "1px"
  },
  borderColors: global.Object.assign({ default: "currentColor" }, colors),
  borderRadius: {},
  width: {
    "px1": "1px",
    "px8": "8px",
    "px16": "16px",
    "px20": "20px",
    "px32": "32px",
    "px40": "40px",
    "px48": "48px",
    "px64": "64px",
    "px128": "128px",
    "px256": "256px",
    "px512": "512px",
    "px768": "768px",
    "px1024": "1024px",
    "px1536": "1536px",
    "pc10": "10%",
    "pc20": "20%",
    "pc25": "25%",
    "pc30": "30%",
    "pc33": "calc(100% / 3)",
    "pc40": "40%",
    "pc50": "50%",
    "pc60": "60%",
    "pc66": "calc(100% / 1.5)",
    "pc70": "70%",
    "pc75": "75%",
    "pc80": "80%",
    "pc90": "90%",
    "pc100": "100%",
    "auto": "auto",
    "min": "min-content",
    "max": "max-content",
    "fit": "fit-content",
  },
  height: {
    "px1": "1px",
    "px8": "8px",
    "px16": "16px",
    "px20": "20px",
    "px24": "24px",
    "px32": "32px",
    "px40": "40px",
    "px48": "48px",
    "px64": "64px",
    "px128": "128px",
    "px256": "256px",
    "pc100": "100%",
    "vh100": "100vh",
    "auto": "auto",
    "min": "min-content",
    "max": "max-content",
  },
  minWidth: {},
  minHeight: {
    "pc100": "100%",
    "vh100": "100vh",
  },
  maxWidth: {
    "px128": "128px",
    "px256": "256px",
    "px512": "512px",
    "px768": "768px",
    "px1024": "1024px",
    "pc100": "100%",
  },
  maxHeight: {},
  padding: {
    "0": "var(--space-0)",
    "4": "var(--space-4)",
    "8": "var(--space-8)",
    "12": "var(--space-12)",
    "16": "var(--space-16)",
    "20": "var(--space-20)",
    "24": "var(--space-24)",
    "32": "var(--space-32)",
    "40": "var(--space-40)",
    "48": "var(--space-48)",
  },
  margin: {
    "auto": "auto",
    "0": "var(--space-0)",
    "4": "var(--space-4)",
    "8": "var(--space-8)",
    "12": "var(--space-12)",
    "16": "var(--space-16)",
    "20": "var(--space-20)",
    "24": "var(--space-24)",
    "32": "var(--space-32)",
    "40": "var(--space-40)",
    "48": "var(--space-48)",
  },
  negativeMargin: {},
  shadows: {
    "1-light": "var(--shadow-1-light)",
    "1-dark": "var(--shadow-1-dark)",
    "4": "var(--shadow-4)",
    "8": "var(--shadow-8)",
    "12": "var(--shadow-12)",
  },
  zIndex: {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "999": 999,
    "9999": 9999,
  },
  opacity: {
    "100": " 1",
    "90": ".9",
    "80": ".8",
    "70": ".7",
    "60": ".6",
    "50": ".5",
    "40": ".4",
    "30": ".3",
    "20": ".2",
    "10": ".1",
    "0": " 0",
  },
  svgFill: {
    "current": "currentColor",
  },
  svgStroke: {
    "current": "currentColor",
  },
  modules: {
    appearance: false,
    backgroundAttachment: false,
    backgroundColors: ["hover", "active"],
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColors: ["hover", "active"],
    borderRadius: false,
    borderStyle: [],
    borderWidths: false,
    cursor: [],
    display: [],
    flexbox: [],
    float: false,
    fonts: [],
    fontWeights: [],
    height: [],
    leading: [],
    lists: false,
    margin: [],
    maxHeight: false,
    maxWidth: [],
    minHeight: [],
    minWidth: false,
    negativeMargin: false,
    objectFit: false,
    objectPosition: false,
    opacity: [],
    outline: false,
    overflow: [],
    padding: [],
    pointerEvents: [],
    position: [],
    resize: false,
    shadows: ["hover"],
    svgFill: [],
    svgStroke: [],
    tableLayout: false,
    textAlign: [],
    textColors: ["hover", "active"],
    textSizes: [],
    textStyle: [],
    tracking: false,
    userSelect: [],
    verticalAlign: [],
    visibility: ["hover", "group-hover"],
    whitespace: [],
    width: [],
    zIndex: [],
  },
  plugins: [],
  options: {
    prefix: "",
    important: false,
    separator: ":",
  },
};
